// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { Transport } from './transport';
import { DiscoveryModule } from './modules/discovery';
import { AudioModule } from './modules/audio';
import { AudioAdminModule } from './modules/audio_admin';
import { AuthModule } from './modules/auth';
import { MultiroomModule } from './modules/multiroom';
import { PlansModule } from './modules/plans';
import { PlansAdminModule } from './modules/plans_admin';
import { PluginsModule } from './modules/plugins';
import { PluginsAdminModule } from './modules/plugins_admin';
import { SubjectsModule } from './modules/subjects';
import { SubjectsAdminModule } from './modules/subjects_admin';
import { SystemModule } from './modules/system';
import { SystemAdminModule } from './modules/system_admin';
import { UiModule } from './modules/ui';
import { UpdatesModule } from './modules/updates';
import { UpdatesAdminModule } from './modules/updates_admin';

/** Top-level client: holds the transport + one property per capability domain. */
export class EvoClient {
  public readonly discovery: DiscoveryModule;
  public readonly audio: AudioModule;
  public readonly audioAdmin: AudioAdminModule;
  public readonly auth: AuthModule;
  public readonly multiroom: MultiroomModule;
  public readonly plans: PlansModule;
  public readonly plansAdmin: PlansAdminModule;
  public readonly plugins: PluginsModule;
  public readonly pluginsAdmin: PluginsAdminModule;
  public readonly subjects: SubjectsModule;
  public readonly subjectsAdmin: SubjectsAdminModule;
  public readonly system: SystemModule;
  public readonly systemAdmin: SystemAdminModule;
  public readonly ui: UiModule;
  public readonly updates: UpdatesModule;
  public readonly updatesAdmin: UpdatesAdminModule;

  public constructor(transport: Transport) {
    this.discovery = new DiscoveryModule(transport);
    this.audio = new AudioModule(transport);
    this.audioAdmin = new AudioAdminModule(transport);
    this.auth = new AuthModule(transport);
    this.multiroom = new MultiroomModule(transport);
    this.plans = new PlansModule(transport);
    this.plansAdmin = new PlansAdminModule(transport);
    this.plugins = new PluginsModule(transport);
    this.pluginsAdmin = new PluginsAdminModule(transport);
    this.subjects = new SubjectsModule(transport);
    this.subjectsAdmin = new SubjectsAdminModule(transport);
    this.system = new SystemModule(transport);
    this.systemAdmin = new SystemAdminModule(transport);
    this.ui = new UiModule(transport);
    this.updates = new UpdatesModule(transport);
    this.updatesAdmin = new UpdatesAdminModule(transport);
  }
}
