// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

// Package: @evo/sdk

export { EvoClient } from './client';
export type { CallOpts, SubscribeOpts, WireOpError, WireOpResult } from './types';

export { DiscoveryModule } from './modules/discovery';
export { AudioModule } from './modules/audio';
export { AudioAdminModule } from './modules/audio_admin';
export { AuthModule } from './modules/auth';
export { MultiroomModule } from './modules/multiroom';
export { PlansModule } from './modules/plans';
export { PlansAdminModule } from './modules/plans_admin';
export { PluginsModule } from './modules/plugins';
export { PluginsAdminModule } from './modules/plugins_admin';
export { SubjectsModule } from './modules/subjects';
export { SubjectsAdminModule } from './modules/subjects_admin';
export { SystemModule } from './modules/system';
export { SystemAdminModule } from './modules/system_admin';
export { UiModule } from './modules/ui';
export { UpdatesModule } from './modules/updates';
export { UpdatesAdminModule } from './modules/updates_admin';
