// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

// Transport abstraction. The runtime mount provides a concrete implementation.

import type { CallOpts, SubscribeOpts, WireOpResult } from './types';

/**
 * Dispatch + subscribe surface every module class consumes.
 *
 * Production implementations target HTTP fetch for `dispatch` and a
 * WebSocket for `subscribe`; tests inject mocks that satisfy the same
 * shape without hitting the network.
 */
export interface Transport {
  dispatch(op: string, payload: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult>;
  subscribe(op: string, payload: Record<string, unknown>, opts?: SubscribeOpts): AsyncIterable<unknown>;
}
