// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

// Shared SDK types.

/** Structured error from the framework's error taxonomy. */
export interface WireOpError {
  readonly code: string;
  readonly message: string;
  /** Framework subclass token (e.g. `plugins_admin_not_granted`,
   *  `peer_not_discovered`, `successor_not_eligible`). Optional in
   *  the wire shape; not all error sites set it. UIs should treat
   *  the message + code as fallback when subclass is absent. */
  readonly subclass?: string;
}

/** Result of a one-shot wire op dispatch. Exactly one of `value` or `error` is set. */
export interface WireOpResult {
  readonly value?: unknown;
  readonly error?: WireOpError;
}

/** Per-call options. The bearer token is presented as a capability-scoped credential; step-up ops require an active step-up session bound to the same token. */
export interface CallOpts {
  readonly stepUpToken?: string;
  readonly signal?: AbortSignal;
}

/** Per-subscription options. Extends `CallOpts` with a `since` cursor for `subscribeHappenings`-class replay. */
export interface SubscribeOpts extends CallOpts {
  readonly since?: number;
}
