// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `audio` capability domain. */
export class AudioModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Read the current active audio topology.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `get_active_audio_topology`
   */
  public async getActiveAudioTopology(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_active_audio_topology', payload ?? {}, opts);
  }

  /**
   * Enumerate every persisted active-audio-topology row.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `list_active_audio_topologies`
   */
  public async listActiveAudioTopologies(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_active_audio_topologies', payload ?? {}, opts);
  }

  /**
   * Read the operator audio policy for one target.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `get_audio_operator_policy`
   */
  public async getAudioOperatorPolicy(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_audio_operator_policy', payload ?? {}, opts);
  }

  /**
   * Enumerate every per-target operator audio policy.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `list_audio_operator_policies`
   */
  public async listAudioOperatorPolicies(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_audio_operator_policies', payload ?? {}, opts);
  }

  /**
   * Read the volume mode for one target.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `get_audio_volume_mode`
   */
  public async getAudioVolumeMode(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_audio_volume_mode', payload ?? {}, opts);
  }

  /**
   * Enumerate every per-target volume mode.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `list_audio_volume_modes`
   */
  public async listAudioVolumeModes(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_audio_volume_modes', payload ?? {}, opts);
  }

  /**
   * Read the hardware profile override for one canonical identity.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `get_hardware_profile_override`
   */
  public async getHardwareProfileOverride(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_hardware_profile_override', payload ?? {}, opts);
  }

  /**
   * Enumerate every hardware profile override.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `list_hardware_profile_overrides`
   */
  public async listHardwareProfileOverrides(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_hardware_profile_overrides', payload ?? {}, opts);
  }

  /**
   * Enumerate every reconciliation pair in the steward.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `list_reconciliation_pairs`
   */
  public async listReconciliationPairs(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_reconciliation_pairs', payload ?? {}, opts);
  }

  /**
   * Project one reconciliation pair by id.
   *
   * Capability: read(audio)
   * Step-up required: no
   * Wire op id: `project_reconciliation_pair`
   */
  public async projectReconciliationPair(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('project_reconciliation_pair', payload ?? {}, opts);
  }
}
