// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `audio_admin` capability domain. */
export class AudioAdminModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Publish a new active audio topology composition.
   *
   * Capability: step-up(audio_admin)
   * Step-up required: yes
   * Wire op id: `publish_active_audio_topology`
   */
  public async publishActiveAudioTopology(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('publish_active_audio_topology', payload ?? {}, opts);
  }

  /**
   * Clear the active audio topology composition.
   *
   * Capability: step-up(audio_admin)
   * Step-up required: yes
   * Wire op id: `clear_active_audio_topology`
   */
  public async clearActiveAudioTopology(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('clear_active_audio_topology', payload ?? {}, opts);
  }

  /**
   * Set the operator audio policy for one target.
   *
   * Capability: write(audio_admin)
   * Step-up required: no
   * Wire op id: `put_audio_operator_policy`
   */
  public async putAudioOperatorPolicy(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('put_audio_operator_policy', payload ?? {}, opts);
  }

  /**
   * Delete the operator audio policy for one target.
   *
   * Capability: write(audio_admin)
   * Step-up required: no
   * Wire op id: `delete_audio_operator_policy`
   */
  public async deleteAudioOperatorPolicy(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('delete_audio_operator_policy', payload ?? {}, opts);
  }

  /**
   * Set the volume mode for one target.
   *
   * Capability: write(audio_admin)
   * Step-up required: no
   * Wire op id: `put_audio_volume_mode`
   */
  public async putAudioVolumeMode(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('put_audio_volume_mode', payload ?? {}, opts);
  }

  /**
   * Delete the volume mode for one target.
   *
   * Capability: write(audio_admin)
   * Step-up required: no
   * Wire op id: `delete_audio_volume_mode`
   */
  public async deleteAudioVolumeMode(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('delete_audio_volume_mode', payload ?? {}, opts);
  }

  /**
   * Set the hardware profile override for one canonical identity.
   *
   * Capability: write(audio_admin)
   * Step-up required: no
   * Wire op id: `put_hardware_profile_override`
   */
  public async putHardwareProfileOverride(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('put_hardware_profile_override', payload ?? {}, opts);
  }

  /**
   * Delete the hardware profile override for one canonical identity.
   *
   * Capability: write(audio_admin)
   * Step-up required: no
   * Wire op id: `delete_hardware_profile_override`
   */
  public async deleteHardwareProfileOverride(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('delete_hardware_profile_override', payload ?? {}, opts);
  }

  /**
   * Force a reconciliation pair to re-evaluate now.
   *
   * Capability: write(audio_admin)
   * Step-up required: no
   * Wire op id: `reconcile_pair_now`
   */
  public async reconcilePairNow(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('reconcile_pair_now', payload ?? {}, opts);
  }
}
