// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `auth` capability domain. */
export class AuthModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Verify operator credentials and issue a step-up auth session.
   *
   * Capability: write(auth)
   * Step-up required: no
   * Wire op id: `step_up_auth_verify`
   */
  public async stepUpAuthVerify(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('step_up_auth_verify', payload ?? {}, opts);
  }

  /**
   * Revoke an active step-up auth session.
   *
   * Capability: write(auth)
   * Step-up required: no
   * Wire op id: `step_up_auth_revoke`
   */
  public async stepUpAuthRevoke(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('step_up_auth_revoke', payload ?? {}, opts);
  }
}
