// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `discovery` capability domain. */
export class DiscoveryModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Discover the wire-protocol version, supported op set, and named features.
   *
   * Capability: anonymous
   * Step-up required: no
   * Wire op id: `describe_capabilities`
   */
  public async describeCapabilities(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('describe_capabilities', payload ?? {}, opts);
  }

  /**
   * Connection handshake. Establish wire-protocol version, capability scope, and session context.
   *
   * Capability: anonymous
   * Step-up required: no
   * Wire op id: `negotiate`
   */
  public async negotiate(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('negotiate', payload ?? {}, opts);
  }
}
