// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `multiroom` capability domain. */
export class MultiroomModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Create a new multi-room group.
   *
   * Capability: write(multiroom)
   * Step-up required: no
   * Wire op id: `create_group`
   */
  public async createGroup(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('create_group', payload ?? {}, opts);
  }

  /**
   * Delete a multi-room group.
   *
   * Capability: write(multiroom)
   * Step-up required: no
   * Wire op id: `delete_group`
   */
  public async deleteGroup(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('delete_group', payload ?? {}, opts);
  }

  /**
   * Rename a multi-room group.
   *
   * Capability: write(multiroom)
   * Step-up required: no
   * Wire op id: `rename_group`
   */
  public async renameGroup(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('rename_group', payload ?? {}, opts);
  }

  /**
   * Add a member device to a multi-room group.
   *
   * Capability: write(multiroom)
   * Step-up required: no
   * Wire op id: `add_group_member`
   */
  public async addGroupMember(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('add_group_member', payload ?? {}, opts);
  }

  /**
   * Remove a member device from a multi-room group.
   *
   * Capability: write(multiroom)
   * Step-up required: no
   * Wire op id: `remove_group_member`
   */
  public async removeGroupMember(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('remove_group_member', payload ?? {}, opts);
  }

  /**
   * Read one multi-room group by id.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `get_group`
   */
  public async getGroup(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_group', payload ?? {}, opts);
  }

  /**
   * Enumerate every multi-room group.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `list_groups`
   */
  public async listGroups(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_groups', payload ?? {}, opts);
  }

  /**
   * Read the active topology of a multi-room group.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `get_group_active_topology`
   */
  public async getGroupActiveTopology(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_group_active_topology', payload ?? {}, opts);
  }

  /**
   * Enumerate the active topology of every multi-room group.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `list_group_active_topologies`
   */
  public async listGroupActiveTopologies(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_group_active_topologies', payload ?? {}, opts);
  }

  /**
   * Dispatch a verb to every member of a multi-room group.
   *
   * Capability: write(multiroom)
   * Step-up required: no
   * Wire op id: `dispatch_to_group`
   */
  public async dispatchToGroup(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('dispatch_to_group', payload ?? {}, opts);
  }

  /**
   * Read the source-host election state for one group.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `get_source_host`
   */
  public async getSourceHost(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_source_host', payload ?? {}, opts);
  }

  /**
   * Enumerate source-host election state for every group.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `list_source_hosts`
   */
  public async listSourceHosts(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_source_hosts', payload ?? {}, opts);
  }

  /**
   * Read the clock-sync state for one group.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `get_clock_sync`
   */
  public async getClockSync(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_clock_sync', payload ?? {}, opts);
  }

  /**
   * Enumerate clock-sync state for every group.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `list_clock_syncs`
   */
  public async listClockSyncs(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_clock_syncs', payload ?? {}, opts);
  }

  /**
   * Enumerate every peer the steward has discovered via mDNS-SD.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `list_discovered_peers`
   */
  public async listDiscoveredPeers(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_discovered_peers', payload ?? {}, opts);
  }

  /**
   * Enumerate admitted gateway plugins for external-ecosystem bridging.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `list_gateway_plugins`
   */
  public async listGatewayPlugins(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_gateway_plugins', payload ?? {}, opts);
  }

  /**
   * Enumerate active audio-plane peer connections.
   *
   * Capability: read(multiroom)
   * Step-up required: no
   * Wire op id: `list_audio_plane_connections`
   */
  public async listAudioPlaneConnections(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_audio_plane_connections', payload ?? {}, opts);
  }
}
