// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `plans_admin` capability domain. */
export class PlansAdminModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Fire a registered listening plan by id.
   *
   * Capability: step-up(plans_admin)
   * Step-up required: yes
   * Wire op id: `fire_plan`
   */
  public async firePlan(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('fire_plan', payload ?? {}, opts);
  }
}
