// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `plans` capability domain. */
export class PlansModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Schedule a time-driven instruction for a plugin.
   *
   * Capability: write(plans)
   * Step-up required: no
   * Wire op id: `create_appointment`
   */
  public async createAppointment(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('create_appointment', payload ?? {}, opts);
  }

  /**
   * Cancel a scheduled appointment.
   *
   * Capability: write(plans)
   * Step-up required: no
   * Wire op id: `cancel_appointment`
   */
  public async cancelAppointment(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('cancel_appointment', payload ?? {}, opts);
  }

  /**
   * Project one appointment by id.
   *
   * Capability: read(plans)
   * Step-up required: no
   * Wire op id: `project_appointment`
   */
  public async projectAppointment(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('project_appointment', payload ?? {}, opts);
  }

  /**
   * Enumerate every scheduled appointment.
   *
   * Capability: read(plans)
   * Step-up required: no
   * Wire op id: `list_appointments`
   */
  public async listAppointments(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_appointments', payload ?? {}, opts);
  }

  /**
   * Schedule a condition-driven instruction for a plugin.
   *
   * Capability: write(plans)
   * Step-up required: no
   * Wire op id: `create_watch`
   */
  public async createWatch(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('create_watch', payload ?? {}, opts);
  }

  /**
   * Cancel a scheduled watch.
   *
   * Capability: write(plans)
   * Step-up required: no
   * Wire op id: `cancel_watch`
   */
  public async cancelWatch(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('cancel_watch', payload ?? {}, opts);
  }

  /**
   * Project one watch by id.
   *
   * Capability: read(plans)
   * Step-up required: no
   * Wire op id: `project_watch`
   */
  public async projectWatch(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('project_watch', payload ?? {}, opts);
  }

  /**
   * Enumerate every scheduled watch.
   *
   * Capability: read(plans)
   * Step-up required: no
   * Wire op id: `list_watches`
   */
  public async listWatches(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_watches', payload ?? {}, opts);
  }
}
