// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `plugins_admin` capability domain. */
export class PluginsAdminModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Enable an admitted plugin's dispatch.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `enable_plugin`
   */
  public async enablePlugin(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('enable_plugin', payload ?? {}, opts);
  }

  /**
   * Disable an admitted plugin's dispatch.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `disable_plugin`
   */
  public async disablePlugin(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('disable_plugin', payload ?? {}, opts);
  }

  /**
   * Bulk-enable admitted plugins matching a filter.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `enable_plugins_where`
   */
  public async enablePluginsWhere(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('enable_plugins_where', payload ?? {}, opts);
  }

  /**
   * Bulk-disable admitted plugins matching a filter.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `disable_plugins_where`
   */
  public async disablePluginsWhere(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('disable_plugins_where', payload ?? {}, opts);
  }

  /**
   * Hot-reload an admitted plugin (cold or live).
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `reload_plugin`
   */
  public async reloadPlugin(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('reload_plugin', payload ?? {}, opts);
  }

  /**
   * Uninstall an admitted plugin and remove its bundle.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `uninstall_plugin`
   */
  public async uninstallPlugin(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('uninstall_plugin', payload ?? {}, opts);
  }

  /**
   * Install a plugin bundle from a remote URL.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `install_plugin_from_url`
   */
  public async installPluginFromUrl(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('install_plugin_from_url', payload ?? {}, opts);
  }

  /**
   * Purge an admitted plugin's persistent state.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `purge_plugin_state`
   */
  public async purgePluginState(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('purge_plugin_state', payload ?? {}, opts);
  }

  /**
   * Create or update a named plugin profile.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `put_plugin_profile`
   */
  public async putPluginProfile(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('put_plugin_profile', payload ?? {}, opts);
  }

  /**
   * Delete a plugin profile by name.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `delete_plugin_profile`
   */
  public async deletePluginProfile(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('delete_plugin_profile', payload ?? {}, opts);
  }

  /**
   * Activate a named plugin profile.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `set_active_plugin_profile`
   */
  public async setActivePluginProfile(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('set_active_plugin_profile', payload ?? {}, opts);
  }

  /**
   * Set a tag on an admitted plugin.
   *
   * Capability: write(plugins_admin)
   * Step-up required: no
   * Wire op id: `set_plugin_tag`
   */
  public async setPluginTag(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('set_plugin_tag', payload ?? {}, opts);
  }

  /**
   * Delete a tag from an admitted plugin.
   *
   * Capability: write(plugins_admin)
   * Step-up required: no
   * Wire op id: `delete_plugin_tag`
   */
  public async deletePluginTag(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('delete_plugin_tag', payload ?? {}, opts);
  }

  /**
   * Register a plugin registry source.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `register_plugin_registry`
   */
  public async registerPluginRegistry(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('register_plugin_registry', payload ?? {}, opts);
  }

  /**
   * Unregister a plugin registry source.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `unregister_plugin_registry`
   */
  public async unregisterPluginRegistry(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('unregister_plugin_registry', payload ?? {}, opts);
  }

  /**
   * Refresh the cached manifest for a registered plugin registry.
   *
   * Capability: write(plugins_admin)
   * Step-up required: no
   * Wire op id: `refresh_plugin_registry`
   */
  public async refreshPluginRegistry(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('refresh_plugin_registry', payload ?? {}, opts);
  }

  /**
   * Grant trust to a plugin publisher's signing key.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `grant_publisher_trust`
   */
  public async grantPublisherTrust(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('grant_publisher_trust', payload ?? {}, opts);
  }

  /**
   * Revoke trust from a plugin publisher's signing key.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `revoke_publisher_trust`
   */
  public async revokePublisherTrust(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('revoke_publisher_trust', payload ?? {}, opts);
  }

  /**
   * Create or update a named admission policy.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `put_admission_policy`
   */
  public async putAdmissionPolicy(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('put_admission_policy', payload ?? {}, opts);
  }

  /**
   * Delete an admission policy by name.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `delete_admission_policy`
   */
  public async deleteAdmissionPolicy(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('delete_admission_policy', payload ?? {}, opts);
  }

  /**
   * Activate a named admission policy.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `set_active_admission_policy`
   */
  public async setActiveAdmissionPolicy(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('set_active_admission_policy', payload ?? {}, opts);
  }

  /**
   * Revoke a specific capability from a plugin.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `revoke_plugin_capability`
   */
  public async revokePluginCapability(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('revoke_plugin_capability', payload ?? {}, opts);
  }

  /**
   * Restore a previously-revoked plugin capability.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `unrevoke_plugin_capability`
   */
  public async unrevokePluginCapability(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('unrevoke_plugin_capability', payload ?? {}, opts);
  }

  /**
   * Reload the distribution catalogue from disk.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `reload_catalogue`
   */
  public async reloadCatalogue(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('reload_catalogue', payload ?? {}, opts);
  }

  /**
   * Reload one plugin's manifest from disk.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `reload_manifest`
   */
  public async reloadManifest(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('reload_manifest', payload ?? {}, opts);
  }

  /**
   * Activate an admitted theme artefact.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `activate_theme`
   */
  public async activateTheme(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('activate_theme', payload ?? {}, opts);
  }

  /**
   * Activate an admitted UI shell artefact.
   *
   * Capability: step-up(plugins_admin)
   * Step-up required: yes
   * Wire op id: `activate_ui_shell`
   */
  public async activateUiShell(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('activate_ui_shell', payload ?? {}, opts);
  }
}
