// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `plugins` capability domain. */
export class PluginsModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Dispatch a plugin request on a specific shelf.
   *
   * Capability: write(plugins)
   * Step-up required: no
   * Wire op id: `request`
   */
  public async request(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('request', payload ?? {}, opts);
  }

  /**
   * Issue a course correction on a custody under a warden's care.
   *
   * Capability: write(plugins)
   * Step-up required: no
   * Wire op id: `course_correct`
   */
  public async courseCorrect(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('course_correct', payload ?? {}, opts);
  }

  /**
   * Assign work to a warden plugin under custody.
   *
   * Capability: write(plugins)
   * Step-up required: no
   * Wire op id: `take_custody`
   */
  public async takeCustody(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('take_custody', payload ?? {}, opts);
  }

  /**
   * Release a custody held by a warden plugin.
   *
   * Capability: write(plugins)
   * Step-up required: no
   * Wire op id: `release_custody`
   */
  public async releaseCustody(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('release_custody', payload ?? {}, opts);
  }

  /**
   * Snapshot every currently-held custody on the steward.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_active_custodies`
   */
  public async listActiveCustodies(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_active_custodies', payload ?? {}, opts);
  }

  /**
   * Enumerate every admitted plugin.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_plugins`
   */
  public async listPlugins(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_plugins', payload ?? {}, opts);
  }

  /**
   * Filter admitted plugins by tag, kind, or admission state.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_plugins_where`
   */
  public async listPluginsWhere(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_plugins_where', payload ?? {}, opts);
  }

  /**
   * Aggregate health snapshot across every admitted plugin.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `get_plugin_health`
   */
  public async getPluginHealth(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_plugin_health', payload ?? {}, opts);
  }

  /**
   * Preview the cascade impact of disabling one plugin.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `preview_dependency_cascade`
   */
  public async previewDependencyCascade(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('preview_dependency_cascade', payload ?? {}, opts);
  }

  /**
   * Read one plugin profile by name.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `get_plugin_profile`
   */
  public async getPluginProfile(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_plugin_profile', payload ?? {}, opts);
  }

  /**
   * Enumerate every plugin profile.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_plugin_profiles`
   */
  public async listPluginProfiles(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_plugin_profiles', payload ?? {}, opts);
  }

  /**
   * Enumerate every tag currently asserted on admitted plugins.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_plugin_tags`
   */
  public async listPluginTags(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_plugin_tags', payload ?? {}, opts);
  }

  /**
   * Enumerate every registered plugin registry source.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_plugin_registries`
   */
  public async listPluginRegistries(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_plugin_registries', payload ?? {}, opts);
  }

  /**
   * Enumerate every trusted plugin publisher.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_publisher_trust`
   */
  public async listPublisherTrust(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_publisher_trust', payload ?? {}, opts);
  }

  /**
   * Read one admission policy by name.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `get_admission_policy`
   */
  public async getAdmissionPolicy(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_admission_policy', payload ?? {}, opts);
  }

  /**
   * Enumerate every admission policy.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_admission_policies`
   */
  public async listAdmissionPolicies(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_admission_policies', payload ?? {}, opts);
  }

  /**
   * Audit a plugin's effective trust against a named policy.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `audit_against_policy`
   */
  public async auditAgainstPolicy(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('audit_against_policy', payload ?? {}, opts);
  }

  /**
   * List active capability revocations for one plugin.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_plugin_capability_revocations`
   */
  public async listPluginCapabilityRevocations(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_plugin_capability_revocations', payload ?? {}, opts);
  }

  /**
   * List every active capability revocation across all plugins.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `list_all_capability_revocations`
   */
  public async listAllCapabilityRevocations(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_all_capability_revocations', payload ?? {}, opts);
  }

  /**
   * Read the currently-active theme and UI shell selection.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `describe_active_ui_selection`
   */
  public async describeActiveUiSelection(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('describe_active_ui_selection', payload ?? {}, opts);
  }

  /**
   * Enumerate every admitted UI stocking across every shelf.
   *
   * Capability: read(plugins)
   * Step-up required: no
   * Wire op id: `describe_ui_stockings`
   */
  public async describeUiStockings(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('describe_ui_stockings', payload ?? {}, opts);
  }
}
