// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `subjects_admin` capability domain. */
export class SubjectsAdminModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Migrate orphaned subjects to a new grammar shape.
   *
   * Capability: step-up(subjects_admin)
   * Step-up required: yes
   * Wire op id: `migrate_grammar_orphans`
   */
  public async migrateGrammarOrphans(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('migrate_grammar_orphans', payload ?? {}, opts);
  }

  /**
   * Mark orphaned subjects accepted in the new grammar.
   *
   * Capability: step-up(subjects_admin)
   * Step-up required: yes
   * Wire op id: `accept_grammar_orphans`
   */
  public async acceptGrammarOrphans(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('accept_grammar_orphans', payload ?? {}, opts);
  }
}
