// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `subjects` capability domain. */
export class SubjectsModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Compose a federated projection for one canonical subject.
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `project_subject`
   */
  public async projectSubject(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('project_subject', payload ?? {}, opts);
  }

  /**
   * Return alias metadata for a canonical subject id.
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `describe_alias`
   */
  public async describeAlias(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('describe_alias', payload ?? {}, opts);
  }

  /**
   * Enumerate every subject the steward knows of.
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `list_subjects`
   */
  public async listSubjects(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_subjects', payload ?? {}, opts);
  }

  /**
   * Enumerate every relation predicate currently asserted.
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `list_relations`
   */
  public async listRelations(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_relations', payload ?? {}, opts);
  }

  /**
   * Enumerate every addressing currently asserted for a subject.
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `enumerate_addressings`
   */
  public async enumerateAddressings(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('enumerate_addressings', payload ?? {}, opts);
  }

  /**
   * Resolve every plugin claimant for a subject.
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `resolve_claimants`
   */
  public async resolveClaimants(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('resolve_claimants', payload ?? {}, opts);
  }

  /**
   * Compose a rack projection (every shelf in one rack).
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `project_rack`
   */
  public async projectRack(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('project_rack', payload ?? {}, opts);
  }

  /**
   * List subjects orphaned by a recent catalogue grammar change.
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `list_grammar_orphans`
   */
  public async listGrammarOrphans(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_grammar_orphans', payload ?? {}, opts);
  }

  /**
   * Subscribe to the durable happenings bus with optional cursor replay.
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `subscribe_happenings`
   */
  public async *subscribeHappenings(payload?: Record<string, unknown>, opts?: SubscribeOpts): AsyncIterable<unknown> {
    yield* this.transport.subscribe('subscribe_happenings', payload ?? {}, opts);
  }

  /**
   * Subscribe to live state changes for one canonical subject.
   *
   * Capability: read(subjects)
   * Step-up required: no
   * Wire op id: `subscribe_subject`
   */
  public async *subscribeSubject(payload?: Record<string, unknown>, opts?: SubscribeOpts): AsyncIterable<unknown> {
    yield* this.transport.subscribe('subscribe_subject', payload ?? {}, opts);
  }
}
