// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `system_admin` capability domain. */
export class SystemAdminModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Set this device's operator-facing display name.
   *
   * Capability: write(system_admin)
   * Step-up required: no
   * Wire op id: `set_device_display_name`
   */
  public async setDeviceDisplayName(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('set_device_display_name', payload ?? {}, opts);
  }

  /**
   * Request a graceful steward restart via the execve coordinator.
   *
   * Capability: step-up(system_admin)
   * Step-up required: yes
   * Wire op id: `request_steward_restart`
   */
  public async requestStewardRestart(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('request_steward_restart', payload ?? {}, opts);
  }

  /**
   * Export the device's configuration substrate as a migration bundle.
   *
   * Capability: step-up(system_admin)
   * Step-up required: yes
   * Wire op id: `export_migration_bundle`
   */
  public async exportMigrationBundle(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('export_migration_bundle', payload ?? {}, opts);
  }

  /**
   * Apply a configuration migration bundle to the device.
   *
   * Capability: step-up(system_admin)
   * Step-up required: yes
   * Wire op id: `import_migration_bundle`
   */
  public async importMigrationBundle(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('import_migration_bundle', payload ?? {}, opts);
  }
}
