// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `system` capability domain. */
export class SystemModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Read this device's persistent identity.
   *
   * Capability: read(system)
   * Step-up required: no
   * Wire op id: `get_device_identity`
   */
  public async getDeviceIdentity(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_device_identity', payload ?? {}, opts);
  }
}
