// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `ui` capability domain. */
export class UiModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Submit an operator answer to an active user-interaction prompt.
   *
   * Capability: write(ui)
   * Step-up required: no
   * Wire op id: `answer_user_interaction`
   */
  public async answerUserInteraction(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('answer_user_interaction', payload ?? {}, opts);
  }

  /**
   * Cancel an active user-interaction prompt.
   *
   * Capability: write(ui)
   * Step-up required: no
   * Wire op id: `cancel_user_interaction`
   */
  public async cancelUserInteraction(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('cancel_user_interaction', payload ?? {}, opts);
  }

  /**
   * Enumerate active user-interaction prompts.
   *
   * Capability: read(ui)
   * Step-up required: no
   * Wire op id: `list_user_interactions`
   */
  public async listUserInteractions(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_user_interactions', payload ?? {}, opts);
  }

  /**
   * Renderer-driven wizard step acknowledgement; advances the persisted resume cursor and (for consent steps) appends an evo.consent ledger entry.
   *
   * Capability: write(ui)
   * Step-up required: no
   * Wire op id: `record_wizard_step_completion`
   */
  public async recordWizardStepCompletion(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('record_wizard_step_completion', payload ?? {}, opts);
  }
}
