// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `updates_admin` capability domain. */
export class UpdatesAdminModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Trigger a manifest fetch from every registered update source.
   *
   * Capability: write(updates_admin)
   * Step-up required: no
   * Wire op id: `check_updates_now`
   */
  public async checkUpdatesNow(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('check_updates_now', payload ?? {}, opts);
  }

  /**
   * Apply a pending update (core or plugins).
   *
   * Capability: step-up(updates_admin)
   * Step-up required: yes
   * Wire op id: `apply_update`
   */
  public async applyUpdate(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('apply_update', payload ?? {}, opts);
  }

  /**
   * Set the auto-apply policy for a target.
   *
   * Capability: step-up(updates_admin)
   * Step-up required: yes
   * Wire op id: `set_auto_apply_policy`
   */
  public async setAutoApplyPolicy(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('set_auto_apply_policy', payload ?? {}, opts);
  }

  /**
   * Set the active update channel for a target.
   *
   * Capability: step-up(updates_admin)
   * Step-up required: yes
   * Wire op id: `set_update_channel`
   */
  public async setUpdateChannel(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('set_update_channel', payload ?? {}, opts);
  }
}
