// generated by evo-projection-core; do not edit
// hand-edits will be overwritten on next regeneration

import type { CallOpts, SubscribeOpts, WireOpResult } from '../types';
import type { Transport } from '../transport';

/** Operations in the `updates` capability domain. */
export class UpdatesModule {
  public constructor(private readonly transport: Transport) {}

  /**
   * Enumerate the current update inventory across every source.
   *
   * Capability: read(updates)
   * Step-up required: no
   * Wire op id: `list_update_inventory`
   */
  public async listUpdateInventory(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('list_update_inventory', payload ?? {}, opts);
  }

  /**
   * Read the auto-apply policy set.
   *
   * Capability: read(updates)
   * Step-up required: no
   * Wire op id: `get_auto_apply_policies`
   */
  public async getAutoApplyPolicies(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_auto_apply_policies', payload ?? {}, opts);
  }

  /**
   * Read the active update channel for core and plugins.
   *
   * Capability: read(updates)
   * Step-up required: no
   * Wire op id: `get_update_channels`
   */
  public async getUpdateChannels(payload?: Record<string, unknown>, opts?: CallOpts): Promise<WireOpResult> {
    return this.transport.dispatch('get_update_channels', payload ?? {}, opts);
  }
}
